---
title: "circosplot_AMLmultiomics"
author: "Tojo James"
date: "09/05/2021"
output: html_document
---

###  Setting clean envt and memory
```{r}
rm(list=ls())
gc()
detach_package <- function(pkg, character.only = FALSE)
{
  if(!character.only)
  {
    pkg <- deparse(substitute(pkg))
  }
  search_item <- paste("package", pkg, sep = ":")
  while(search_item %in% search())
  {
    detach(search_item, unload = TRUE, character.only = TRUE)
  }
}
detach_package("plyr", TRUE)
```


### Read datafile

```{r}
library("xlsx")
Patient_drugs <- read.xlsx(file="/home/tojo.james/AMLmultiomics/circosDrugRankTableTop5percentage.xlsx", sheetIndex=1, header=TRUE, colClasses=NA)
rownames(Patient_drugs) <- Patient_drugs$DRUG_NAME
Patient_drugs_selected <- as.data.frame(t(Patient_drugs[7:ncol(Patient_drugs)-1]))
table(Patient_drugs_selected$Triciribine + Patient_drugs_selected$Navitoclax)
drugpairs <-as.data.frame(t(combn(colnames(Patient_drugs_selected), 2)))
as.character(drugpairs$V2[2])
x = 2
table(Patient_drugs_selected[[as.character(drugpairs$V1[1])]] + Patient_drugs_selected[[as.character(drugpairs$V2[1])]])


print(as.character(drugpairs$V2[1]))
matched <- c()

for (i in 1:nrow(drugpairs)){
  print(as.character(drugpairs$V2[i]))
  col <- length(which(c(Patient_drugs_selected[[as.character(drugpairs$V1[i])]] + Patient_drugs_selected[[as.character(drugpairs$V2[i])]])==x))
  matched <- append(matched, col)
}
drugpairs$count_matched <- matched

drugpairs[order(drugpairs$count_matched, decreasing = TRUE),]
colnames(drugpairs) <- c("from","to","value")

drugpairs <- as.data.frame(drugpairs)
meta_patient_drugs <-Patient_drugs[c("Mechanism.Targets","Class.explained","High.phase.Approval.status","DRUG_NAME")]


drugpairs_meta_a <-  merge(x=meta_patient_drugs,y=drugpairs,by.x=c("DRUG_NAME"),by.y=("from"),all.y=TRUE)
all_drugpairs_meta <- merge(x=drugpairs_meta_a,y=meta_patient_drugs,by.x=c("to"),by.y=c("DRUG_NAME"),all.x=TRUE)

colnames(all_drugpairs_meta) <- c("to","from","Mechanism.Targets_from","Class.explained_from","High.phase.Approval.status_from","value","Mechanism.Targets_to","Class.explained_to","High.phase.Approval.status_to")


all_drugpairs_meta

?chordDiagram
chordDiagram(drugpairs)

```

```{r}
# original image
library(circlize)
mat <- drugpairs
grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))

mat[order(mat$value,decreasing = TRUE),]

#chordDiagram(mat, grid.col = grid.col) 

# now, the image with rotated labels
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)
```

### Chord diagram matched classes

```{r}
dim(all_drugpairs_meta)
dim(mat)
matched_class_drugpairs <- all_drugpairs_meta[(all_drugpairs_meta$Class.explained_from == all_drugpairs_meta$Class.explained_to),][c("from","to","value")]
dim(matched_class_drugpairs)
797/3321


mat <- matched_class_drugpairs
grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))

#chordDiagram(mat, grid.col = grid.col) 

# now, the image with rotated labels
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)


```


### Chord diagram unique classes

```{r}
dim(all_drugpairs_meta)
dim(mat)
unique_class_drugpairs <- all_drugpairs_meta[(all_drugpairs_meta$Class.explained_from != all_drugpairs_meta$Class.explained_to),][c("from","to","value")]
dim(unique_class_drugpairs)
797/3321

unique(all_drugpairs_meta$Class.explained_from)

mat <- unique_class_drugpairs
grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))

#chordDiagram(mat, grid.col = grid.col) 

# now, the image with rotated labels
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)


```

#### Based on classes
```{r}
dim(all_drugpairs_meta)
dim(mat)
unique_class_drugpairs <- all_drugpairs_meta[(all_drugpairs_meta$Class.explained_from != all_drugpairs_meta$Class.explained_to),][c("Class.explained_from","Class.explained_to","value")]
dim(unique_class_drugpairs)

colnames(unique_class_drugpairs) <- c("from","to","value")

797/3321

unique(all_drugpairs_meta$Class.explained_from)

mat <- unique_class_drugpairs
grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))

#chordDiagram(mat, grid.col = grid.col) 

# now, the image with rotated labels
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)


```



### Reading meta and sdss
```{r}

library("xlsx")
AML_Patient_drugs <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=1, header=TRUE, colClasses=NA)
AML_Patient_drugs <- AML_Patient_drugs[1:528,]
meta_Patient_drugs <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=2, header=TRUE, colClasses=NA)
meta_Patient_drugs
drug_info <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=3, header=TRUE, colClasses=NA)
drug_info <- drug_info[,1:5]
tail(AML_Patient_drugs)

rownames(AML_Patient_drugs) <- AML_Patient_drugs$DRUG_NAME

AML_Patient_drugs <- AML_Patient_drugs[,-which(names(AML_Patient_drugs) %in% c("DRUG_NAME","FIMM_ID","Medel"))]
colnames(AML_Patient_drugs)


AML_Patient_drugs <- as.data.frame(t(AML_Patient_drugs))
#AML_Patient_drugs <- AML_Patient_drugs[,-which(names(AML_Patient_drugs) %in% c("DRUG_NAME"))]
colnames(AML_Patient_drugs)

k=2
highest_2_drug.patient <- t(apply(AML_Patient_drugs,1,function(x)names(AML_Patient_drugs)[sort(head(order(x,decreasing=TRUE),k))]))
highest_2_drug.patient <- as.data.frame(highest_2_drug.patient)
colnames(highest_2_drug.patient) <- c("from","to")
rownames(highest_2_drug.patient) <- NULL
highest_2_drug.patient$value <- 1

```
### Create circos plot
```{r}

mat <-highest_2_drug.patient
grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)


```

### Class
```{r}
meta_patient_drugs <-drug_info[c("Mechanism.Targets","Class.explained","High.phase.Approval.status","DRUG_NAME")]


highest_2_drug.patient_meta_a <-  merge(x=meta_patient_drugs,y=highest_2_drug.patient,by.x=c("DRUG_NAME"),by.y=("from"),all.y=TRUE)
colnames(highest_2_drug.patient_meta_a) <- c("from","Mechanism.Targets_from","Class.explained_from","High.phase.Approval.status_from","to","value")

all_highest_2_drug.patient_meta <- merge(x=highest_2_drug.patient_meta_a,y=meta_patient_drugs,by.x=c("to"),by.y=c("DRUG_NAME"),all.x=TRUE)

colnames(all_highest_2_drug.patient_meta) <- c("to","from","Mechanism.Targets_from","Class.explained_from","High.phase.Approval.status_from","value","Mechanism.Targets_to","Class.explained_to","High.phase.Approval.status_to")

write.xlsx(all_highest_2_drug.patient_meta,file="/home/tojo.james/AMLmultiomics/drug_top2_indiv_classes_gephi.xlsx")

dim(all_highest_2_drug.patient_meta)

dim(all_highest_2_drug.patient_meta[all_highest_2_drug.patient_meta$Class.explained_from==all_highest_2_drug.patient_meta$Class.explained_to,])

dim(all_highest_2_drug.patient_meta[all_highest_2_drug.patient_meta$Mechanism.Targets_from==all_highest_2_drug.patient_meta$Mechanism.Targets_to,])


```

### Unique 

```{r}
unique_class_drugpairs <- all_highest_2_drug.patient_meta[(all_highest_2_drug.patient_meta$Class.explained_from != all_highest_2_drug.patient_meta$Class.explained_to),]

unique_class_drugpairs <- unique_class_drugpairs[order(unique_class_drugpairs$Class.explained_from),]

unique_class_drugpairs <- unique_class_drugpairs[c("Class.explained_from","from","to","value")]

dim(unique_class_drugpairs)

colnames(unique_class_drugpairs) <- c("Class.explained_from","from","to","value")

797/3321

#unique(all_drugpairs_meta$Class.explained_from)

mat <- unique_class_drugpairs

grid.col <- setNames(rainbow(length(unlist(dimnames(mat)))), union(rownames(mat), colnames(mat)))
par(mar = c(0, 0, 0, 0), mfrow = c(1, 2))
chordDiagram(mat, annotationTrack = "grid", preAllocateTracks = 1, grid.col = grid.col)
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1] + .1, sector.name, facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
  circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2, sector.index = sector.name, track.index = 2)
}, bg.border = NA)


highlight.sector(mat$Class.explained_from, track.index = 2, col = "red", 
    text = "A", cex = 0.2, text.col = "white", niceFacing = TRUE,"track.height" = 0.1)
highlight.sector(colnames(mat1), track.index = 1, col = "green", 
    text = "B", cex = 0.8, text.col = "white", niceFacing = TRUE)
highlight.sector(colnames(mat2), track.index = 1, col = "blue", 
    text = "C", cex = 0.8, text.col = "white", niceFacing = TRUE)

```
### Multilayer
```{r}
df <- unique_class_drugpairs

library(circlize)
library(RColorBrewer)
mycolors = rep(c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 6)),10)
mycolors[1:10]
all_classes = unique(df[[1]])
color_classes = structure(mycolors[1:length(all_classes)], names = all_classes)
all_drugs = unique(c(df[[2]], df[[3]]))
color_drugs = structure(mycolors[1:length(all_drugs)], names = all_drugs)
length(color_drugs )
```



### Example
```{r}
df = read.table(textConnection(
"import_region    export_region  species                flow
North_America    Europe         Acanthosaura_armata     0.0104
Southeast_Asia   Europe         Acanthosaura_armata     0.0022
Indonesia        Europe         Acanthosaura_armata     0.1971
Indonesia        Europe         Acrochordus_granulatus  0.7846
Southeast_Asia   Europe         Acrochordus_granulatus  0.1101
Indonesia        Europe         Acrochordus_javanicus   2.00E-04
Southeast_Asia   Europe         Acrochordus_javanicus   0.0015
Indonesia        North_America  Acrochordus_javanicus   0.0024
East_Asia        Europe         Acrochordus_javanicus   0.0028
Indonesia        Europe         Ahaetulla_prasina       4.00E-04
Southeast_Asia   Europe         Ahaetulla_prasina       4.00E-04
Southeast_Asia   East_Asia      Amyda_cartilaginea      0.0027
Indonesia        East_Asia      Amyda_cartilaginea      5.00E-04
Indonesia        Europe         Amyda_cartilaginea      0.004
Indonesia        Southeast_Asia Amyda_cartilaginea      0.0334
Europe           North_America  Amyda_cartilaginea      4.00E-04
Indonesia        North_America  Amyda_cartilaginea      0.1291
Southeast_Asia   Southeast_Asia Amyda_cartilaginea      0.0283
Indonesia        West_Asia      Amyda_cartilaginea      0.7614
South_Asia       Europe         Amyda_cartilaginea      2.8484
Australasia      Europe         Apodora_papuana         0.0368
Indonesia        North_America  Apodora_papuana         0.324
Indonesia        Europe         Apodora_papuana         0.0691
Europe           Europe         Apodora_papuana         0.0106
Indonesia        East_Asia      Apodora_papuana         0.0129
Europe           North_America  Apodora_papuana         0.0034
East_Asia        East_Asia      Apodora_papuana         2.00E-04
Indonesia        Southeast_Asia Apodora_papuana         0.0045
East_Asia        North_America  Apodora_papuans         0.0042"),
header = TRUE, stringsAsFactors = FALSE)

df = df[df[[4]] > 0.01, ]


library(circlize)
library(RColorBrewer)
all_species = unique(df[[3]])
color_species = structure(brewer.pal(length(all_species), "Set1"), names = all_species)
all_regions = unique(c(df[[1]], df[[2]]))
color_regions = structure(brewer.pal(length(all_regions), "Set2"), names = all_regions)


## group by regions
df2 = data.frame(from = paste(df[[1]], df[[3]], sep = "|"),
                 to = paste(df[[2]], df[[3]], sep = "|"),
                 value = df[[4]], stringsAsFactors = FALSE)

combined = unique(data.frame(regions = c(df[[1]], df[[2]]), 
    species = c(df[[3]], df[[3]]), stringsAsFactors = FALSE))
combined = combined[order(combined$regions, combined$species), ]
order = paste(combined$regions, combined$species, sep = "|")
grid.col = structure(color_species[combined$species], names = order)

gap = rep(1, length(order))
gap[which(!duplicated(combined$species, fromLast = TRUE))] = 5

circos.par(gap.degree = gap)
chordDiagram(df2, order = order, annotationTrack = c("grid", "axis"),
    grid.col = grid.col, directional = TRUE,
    preAllocateTracks = list(
        track.height = 0.04,
        track.margin = c(0.05, 0)
    )
)
for(region in unique(combined$regions)) {
    l = combined$regions == region
    sn = paste(combined$regions[l], combined$species[l], sep = "|")
    highlight.sector(sn, track.index = 1, col = color_regions[region], 
        text = region, niceFacing = TRUE)
}
circos.clear()

legend("bottomleft", pch = 15, col = color_regions, 
    legend = names(color_regions), cex = 0.6)
legend("bottomright", pch = 15, col = color_species, legend = names(color_species), cex = 0.6)


```
### Circos plot drug-class
```{r}
#unique_class_drugpairs
drug_classes <- unique(c(as.character(all_drugpairs_meta$Class.explained_from),as.character(all_drugpairs_meta$Class.explained_to)))
all_drugpairs_meta <- all_drugpairs_meta[c("from","to","Class.explained_from","Class.explained_to","value")]
#all_drugpairs_meta$value <- 1
all_drugpairs_meta <- all_drugpairs_meta[all_drugpairs_meta$value!=0,]
all_drugpairs_meta <- all_drugpairs_meta[order(all_drugpairs_meta$Class.explained_from),]
par(xpd=FALSE)
#unique(all_drugpairs_meta$to)
#,"D. Immunomodulatory"
drug_classes <- c("A. Conv. Chemo","B. Kinase inhibitor","D. Immunomodulatory","E. Differentiating/ epigenetic modifier","G. Apoptotic modulator","H. Metabolic modifier","I. Kinesin inhibitor","K. HSP inhibitor", "L. Protease/proteasome inhibitor","X. Other")
drug_classes <- drug_classes[10]
# plot_list = list()
# for (cc in drug_classes) {
#   print(cc)
#   file_name = paste("circos_class_", cc, ".png", sep="")
#   png(file_name)
#   print(plot_list[[i]])
#   dev.off()
# }
plot_list = list()
#png("/home/tojo.james/AMLmultiomics/circos_allclasses.png") 
for (cc in drug_classes) {
  df_1 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_from ==cc,]
  df_2 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_to ==cc,]
  colnames(df_2) <- c("to","from","Class.explained_to","Class.explained_from","value")
  
  df_1 <- df_1[c("to","from","Class.explained_to","Class.explained_from","value")]
  df <- rbind(df_2,df_1)
  #df <- df[df$Class.explained_from==df$Class.explained_to,]
  df <- df[order(df$Class.explained_to),]
  #df <- df[c("to","from","Class.explained_to","Class.explained_from","value")]
  
  #table(df$Class.explained_to)
  #table(paste0(df_1$to,"--",df_1$from)) + table(paste0(df_1$from,"--",df_1$to))
  
  #df <- as.data.frame(all_drugpairs_meta,stringsAsFactors = FALSE)[2000:2500,]
  #df <- df_2
  library(circlize)
  library(RColorBrewer)
  mycolors = rep(c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 6)),10)
  all_drugs = unique(c(as.character(df[[1]]),as.character(df[[2]])))
  color_drugs = structure(mycolors[1:length(all_drugs)], names = all_drugs)
  all_classes = unique(c(as.character(df[[3]]), as.character(df[[4]])))
  color_classes = structure(mycolors[1:length(all_classes)], names = all_classes)
  
  ## group by regions
  df2 = data.frame(from = paste(df[[1]], df[[3]], sep = "|"),
                   to = paste(df[[2]], df[[4]], sep = "|"),
                   value = df[[5]], stringsAsFactors = FALSE)
  #df2 <- df2[df2$value!=0,]
  combined = unique(data.frame(classes = c(as.character(df[[1]]), as.character(df[[2]])), 
      drugs = c(as.character(df[[3]]), as.character(df[[4]])), stringsAsFactors = FALSE))
  combined = combined[order(combined$drugs,combined$classes),]
  order = paste(combined$classes, combined$drugs, sep = "|")
  grid.col = structure(color_classes[combined$drugs], names = order)
  
  gap = rep(1, length(order))
  gap[which(!duplicated(combined$drugs, fromLast = TRUE))] = 5
  
  ?circos.par
  circos.par(gap.degree = gap)
  chordDiagram(df2, order = order,reduce = 0,
   annotationTrack = c("grid"),
      grid.col = grid.col, directional = FALSE,
      preAllocateTracks = list(
          track.height = 0.02,
          track.margin = c(0.05, 0)
      )
  )
  for(class in unique(combined$classes)) {
      l = combined$classes == class
      sn = paste(combined$classes[l], combined$drugs[l], sep = "|")
      highlight.sector(sn, track.index = 1, col = color_classes[class], 
          text = class, niceFacing = TRUE,cex =0.8,facing = "clockwise")
  }
circos.clear()
legend("bottomright", pch = 20, col = color_classes,  legend = names(color_classes), cex = 1,pt.cex=1.8)  
}    
#dev.off()

legend("bottomright", pch = 20, col = color_classes,  legend = names(color_classes), cex = 0.6)
?legend
# ?chordDiagram
#legend("bottomright", pch = 15, col = color_drugs, legend = names(color_drugs), cex = 0.6)
#df

```

### Drug dataset
```{r}
library("xlsx")
AML_Patient_drugs <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=1, header=TRUE, colClasses=NA)
AML_Patient_drugs <- AML_Patient_drugs[1:528,]
meta_Patient_drugs <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=2, header=TRUE, colClasses=NA)
meta_Patient_drugs
drug_info <- read.xlsx(file="/home/tojo.james/AMLmultiomics/Circos_AML_drugmeta_sdss.xlsx", sheetIndex=3, header=TRUE, colClasses=NA)
drug_info <- drug_info[,1:5]
tail(AML_Patient_drugs)

rownames(AML_Patient_drugs) <- AML_Patient_drugs$DRUG_NAME

AML_Patient_drugs <- AML_Patient_drugs[,-which(names(AML_Patient_drugs) %in% c("DRUG_NAME","FIMM_ID","Medel"))]
colnames(AML_Patient_drugs)


AML_Patient_drugs <- as.data.frame(t(AML_Patient_drugs))
#AML_Patient_drugs <- AML_Patient_drugs[,-which(names(AML_Patient_drugs) %in% c("DRUG_NAME"))]
colnames(AML_Patient_drugs)

library(dplyr)
AML_Patient_drugs <- as.data.frame(AML_Patient_drugs %>% mutate_if(is.numeric, ~1 * (. > 7)))
AML_Patient_drugs[is.na(AML_Patient_drugs)] = 0
test <- AML_Patient_drugs
test["Total"] <- rowSums(test)

significant_dsscounts <- test[c("Total")]

rownames(meta_Patient_drugs) <- meta_Patient_drugs$Sample

meta_dss_patients <- merge(meta_Patient_drugs,significant_dsscounts,by=c("row.names"))[c("Sample","Viability","Fresh","Total")]

meta_dss_patients <- meta_dss_patients[complete.cases(meta_dss_patients), ]
meta_dss_patients <- meta_dss_patients[meta_dss_patients$Viability!="na",]
cor.test(meta_dss_patients$Fresh,meta_dss_patients$Total)
table(meta_dss_patients$Fresh)
boxplot(as.factor(meta_dss_patients$Fresh),meta_dss_patients$Total)
cor.test(as.numeric(as.character(meta_dss_patients$Viability)),meta_dss_patients$Total)
plot(as.numeric(as.character(meta_dss_patients$Viability)),meta_dss_patients$Total)

cor.test(as.numeric(as.character(meta_dss_patients$Viability)),meta_dss_patients$Fresh)

```


### circos plot
```{r}
drugpairs <-as.data.frame(t(combn(colnames(AML_Patient_drugs), 2)))
as.character(drugpairs$V2[2])
x = 2
table(AML_Patient_drugs[[as.character(drugpairs$V1[1])]] + AML_Patient_drugs[[as.character(drugpairs$V2[1])]])


print(as.character(drugpairs$V2[1]))
matched <- c()

for (i in 1:nrow(drugpairs)){
  print(as.character(drugpairs$V2[i]))
  col <- length(which(c(AML_Patient_drugs[[as.character(drugpairs$V1[i])]] + AML_Patient_drugs[[as.character(drugpairs$V2[i])]])==x))
  matched <- append(matched, col)
}
drugpairs$count_matched <- matched
drugpairs <- drugpairs[drugpairs$count_matched != 0,]
drugpairs[order(drugpairs$count_matched,decreasing = TRUE),][1:100,]

significant_drugs_comb <- drugpairs

colnames(significant_drugs_comb) <- c("from","to","value")

meta_patient_drugs <-drug_info[c("Mechanism.Targets","Class.explained","High.phase.Approval.status","DRUG_NAME")]


significant_drugs_comb_meta_a <-  merge(x=meta_patient_drugs,y=significant_drugs_comb,by.x=c("DRUG_NAME"),by.y=("from"),all.y=TRUE)
colnames(significant_drugs_comb_meta_a) <- c("from","Mechanism.Targets_from","Class.explained_from","High.phase.Approval.status_from","to","value")

significant_drugs_comb_meta <- merge(x=significant_drugs_comb_meta_a,y=meta_patient_drugs,by.x=c("to"),by.y=c("DRUG_NAME"),all.x=TRUE)

colnames(significant_drugs_comb_meta) <- c("to","from","Mechanism.Targets_from","Class.explained_from","High.phase.Approval.status_from","value","Mechanism.Targets_to","Class.explained_to","High.phase.Approval.status_to")



```

### Circos plot

```{r}
all_drugpairs_meta <- significant_drugs_comb_meta[c("from","to","Class.explained_from","Class.explained_to","value")]
all_drugpairs_meta <- all_drugpairs_meta[order(all_drugpairs_meta$value, decreasing=TRUE),][1:1100,]
all_drugpairs_meta <- all_drugpairs_meta[all_drugpairs_meta$value!=0,]
all_drugpairs_meta <- all_drugpairs_meta[order(all_drugpairs_meta$Class.explained_from),]
par(xpd=FALSE)
#unique(all_drugpairs_meta$to)
#,"D. Immunomodulatory"
drug_classes <- c("A. Conv. Chemo","B. Kinase inhibitor","D. Immunomodulatory","E. Differentiating/ epigenetic modifier","G. Apoptotic modulator","H. Metabolic modifier","I. Kinesin inhibitor","K. HSP inhibitor", "L. Protease/proteasome inhibitor","X. Other")
drug_classes <- drug_classes[5]
# plot_list = list()
# for (cc in drug_classes) {
#   print(cc)
#   file_name = paste("circos_class_", cc, ".png", sep="")
#   png(file_name)
#   print(plot_list[[i]])
#   dev.off()
# }
plot_list = list()
#png("/home/tojo.james/AMLmultiomics/circos_allclasses.png") 
for (cc in drug_classes) {
  df_1 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_from ==cc,]
  df_2 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_to ==cc,]
  colnames(df_2) <- c("to","from","Class.explained_to","Class.explained_from","value")
  
  df_1 <- df_1[c("to","from","Class.explained_to","Class.explained_from","value")]
  df <- rbind(df_2,df_1)
  #df <- df[df$Class.explained_from==df$Class.explained_to,]
  df <- df[order(df$Class.explained_to),]
  #df <- df[c("to","from","Class.explained_to","Class.explained_from","value")]
  
  #table(df$Class.explained_to)
  #table(paste0(df_1$to,"--",df_1$from)) + table(paste0(df_1$from,"--",df_1$to))
  
  #df <- as.data.frame(all_drugpairs_meta,stringsAsFactors = FALSE)[2000:2500,]
  #df <- df_2
  library(circlize)
  library(RColorBrewer)
  mycolors = rep(c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 6)),10)
  all_drugs = unique(c(as.character(df[[1]]),as.character(df[[2]])))
  color_drugs = structure(mycolors[1:length(all_drugs)], names = all_drugs)
  all_classes = unique(c(as.character(df[[3]]), as.character(df[[4]])))
  color_classes = structure(mycolors[1:length(all_classes)], names = all_classes)
  
  ## group by regions
  df2 = data.frame(from = paste(df[[1]], df[[3]], sep = "|"),
                   to = paste(df[[2]], df[[4]], sep = "|"),
                   value = df[[5]], stringsAsFactors = FALSE)
  #df2 <- df2[df2$value!=0,]
  combined = unique(data.frame(classes = c(as.character(df[[1]]), as.character(df[[2]])), 
      drugs = c(as.character(df[[3]]), as.character(df[[4]])), stringsAsFactors = FALSE))
  combined = combined[order(combined$drugs,combined$classes),]
  order = paste(combined$classes, combined$drugs, sep = "|")
  grid.col = structure(color_classes[combined$drugs], names = order)
  
  gap = rep(1, length(order))
  gap[which(!duplicated(combined$drugs, fromLast = TRUE))] = 5
  
  ?circos.par
  circos.par(gap.degree = gap)
  chordDiagram(df2, order = order,reduce = 0,
   annotationTrack = c("grid"),
      grid.col = grid.col, directional = FALSE,
      preAllocateTracks = list(
          track.height = 0.02,
          track.margin = c(0.05, 0)
      )
  )
  for(class in unique(combined$classes)) {
      l = combined$classes == class
      sn = paste(combined$classes[l], combined$drugs[l], sep = "|")
      highlight.sector(sn, track.index = 1, col = color_classes[class], 
          text = class, niceFacing = TRUE,cex =0.8,facing = "clockwise")
  }
circos.clear()
}
```
### Drug specific

```{r}
significant_drugs_comb_meta$Mechanism.Targets_from
significant_drugs_comb_meta[significant_drugs_comb_meta$from=="Venetoclax",]

all_drugpairs_meta <- significant_drugs_comb_meta[c("from","to","Mechanism.Targets_from","Mechanism.Targets_to","value")]
colnames(all_drugpairs_meta) <-c("from","to","Class.explained_from","Class.explained_to","value")
all_drugpairs_meta <- all_drugpairs_meta[order(all_drugpairs_meta$value, decreasing=TRUE),][1:1000,]
all_drugpairs_meta <- all_drugpairs_meta[all_drugpairs_meta$value!=0,]
all_drugpairs_meta <- all_drugpairs_meta[order(all_drugpairs_meta$value),]
par(xpd=FALSE)
#unique(all_drugpairs_meta$to)
#,"D. Immunomodulatory"
drug_selected<- c("Bcl-2-selective inhibitor")
drug_classes <- drug_classes[5]
# plot_list = list()
# for (cc in drug_classes) {
#   print(cc)
#   file_name = paste("circos_class_", cc, ".png", sep="")
#   png(file_name)
#   print(plot_list[[i]])
#   dev.off()
# }
plot_list = list()
#png("/home/tojo.james/AMLmultiomics/circos_allclasses.png") 
for (cc in drug_selected) {
  df_1 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_from ==cc,]
  df_2 <- all_drugpairs_meta[all_drugpairs_meta$Class.explained_to ==cc,]
  colnames(df_2) <- c("to","from","Class.explained_to","Class.explained_from","value")
  
  df_1 <- df_1[c("to","from","Class.explained_to","Class.explained_from","value")]
  df <- rbind(df_2,df_1)
  #df <- df[df$Class.explained_from==df$Class.explained_to,]
  df <- df[order(df$value),]
  #df <- df[c("to","from","Class.explained_to","Class.explained_from","value")]
  
  #table(df$Class.explained_to)
  #table(paste0(df_1$to,"--",df_1$from)) + table(paste0(df_1$from,"--",df_1$to))
  
  #df <- as.data.frame(all_drugpairs_meta,stringsAsFactors = FALSE)[2000:2500,]
  #df <- df_2
  library(circlize)
  library(RColorBrewer)
  mycolors = rep(c(brewer.pal(name="Dark2", n = 8), brewer.pal(name="Paired", n = 6)),50)
  all_drugs = unique(c(as.character(df[[1]]),as.character(df[[2]])))
  color_drugs = structure(mycolors[1:length(all_drugs)], names = all_drugs)
  all_classes = unique(c(as.character(df[[3]]), as.character(df[[4]])))
  color_classes = structure(mycolors[1:length(all_classes)], names = all_classes)
  
  ## group by regions
  df2 = data.frame(from = paste(df[[1]], df[[3]], sep = "|"),
                   to = paste(df[[2]], df[[4]], sep = "|"),
                   value = df[[5]], stringsAsFactors = FALSE)
  #df2 <- df2[df2$value!=0,]
  combined = unique(data.frame(classes = c(as.character(df[[1]]), as.character(df[[2]])), 
      drugs = c(as.character(df[[3]]), as.character(df[[4]])), stringsAsFactors = FALSE))
  combined = combined[order(combined$drugs,combined$classes),]
  order = paste(combined$classes, combined$drugs, sep = "|")
  grid.col = structure(color_classes[combined$drugs], names = order)
  
  gap = rep(1, length(order))
  gap[which(!duplicated(combined$drugs, fromLast = TRUE))] = 5
  
  ?circos.par
  circos.par(gap.degree = gap)
  chordDiagram(df2, order = order,reduce = 0,
   annotationTrack = c("grid"),
      grid.col = grid.col, directional = FALSE,
      preAllocateTracks = list(
          track.height = 0.02,
          track.margin = c(0.05, 0)
      )
  )
  for(class in unique(combined$classes)) {
      l = combined$classes == class
      sn = paste(combined$classes[l], combined$drugs[l], sep = "|")
      highlight.sector(sn, track.index = 1, col = color_classes[class], 
          text = class, niceFacing = TRUE,cex =0.8,facing = "clockwise")
  }
circos.clear()
}
```



### example circos

```{r}
# Libraries
library(ggraph)
library(igraph)
library(tidyverse)
library(RColorBrewer)
 
# create a data frame giving the hierarchical structure of your individuals
set.seed(1234)
d1 <- data.frame(from="origin", to=paste("group", seq(1,10), sep=""))
d2 <- data.frame(from=rep(d1$to, each=10), to=paste("subgroup", seq(1,100), sep="_"))
edges <- rbind(d1, d2)
 
# create a dataframe with connection between leaves (individuals)
all_leaves <- paste("subgroup", seq(1,100), sep="_")
connect <- rbind( 
  data.frame( from=sample(all_leaves, 100, replace=T) , to=sample(all_leaves, 100, replace=T)), 
  data.frame( from=sample(head(all_leaves), 30, replace=T) , to=sample( tail(all_leaves), 30, replace=T)), 
  data.frame( from=sample(all_leaves[25:30], 30, replace=T) , to=sample( all_leaves[55:60], 30, replace=T)), 
  data.frame( from=sample(all_leaves[75:80], 30, replace=T) , to=sample( all_leaves[55:60], 30, replace=T)) )
connect$value <- runif(nrow(connect))
 
# create a vertices data.frame. One line per object of our hierarchy
vertices  <-  data.frame(
  name = unique(c(as.character(edges$from), as.character(edges$to))) , 
  value = runif(111)
) 
# Let's add a column with the group of each name. It will be useful later to color points
vertices$group  <-  edges$from[ match( vertices$name, edges$to ) ]



# Create a graph object
mygraph <- igraph::graph_from_data_frame( edges, vertices=vertices )
 
# The connection object must refer to the ids of the leaves:
from  <-  match( connect$from, vertices$name)
to  <-  match( connect$to, vertices$name)


#Let's add information concerning the label we are going to add: angle, horizontal adjustement and potential flip
#calculate the ANGLE of the labels
vertices$id <- NA
myleaves <- which(is.na( match(vertices$name, edges$from) ))
nleaves <- length(myleaves)
vertices$id[ myleaves ] <- seq(1:nleaves)
vertices$angle <- 90 - 360 * vertices$id / nleaves
 
# calculate the alignment of labels: right or left
# If I am on the left part of the plot, my labels have currently an angle < -90
vertices$hjust <- ifelse( vertices$angle < -90, 1, 0)
 
# flip angle BY to make them readable
vertices$angle <- ifelse(vertices$angle < -90, vertices$angle+180, vertices$angle)


# Basic usual argument
ggraph(mygraph, layout = 'dendrogram', circular = TRUE) + 
  geom_node_point(aes(filter = leaf, x = x*1.05, y=y*1.05)) +
  geom_conn_bundle(data = get_con(from = from, to = to), alpha=0.2, colour="skyblue", width=0.9) +
  geom_node_text(aes(x = x*1.1, y=y*1.1, filter = leaf, label=name, angle = vertices$angle, hjust=vertices$hjust), size=1.5, alpha=1) +
  theme_void() +
  theme(
    legend.position="none",
    plot.margin=unit(c(0,0,0,0),"cm"),
  ) +
  expand_limits(x = c(-1.2, 1.2), y = c(-1.2, 1.2))
```

```{r}
# Libraries
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(chorddiag)  #devtools::install_github("mattflor/chorddiag")

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/13_AdjacencyDirectedWeighted.csv", header=TRUE)

# short names
colnames(data) <- c("Africa", "East Asia", "Europe", "Latin Ame.",   "North Ame.",   "Oceania", "South Asia", "South East Asia", "Soviet Union", "West.Asia")
rownames(data) <- colnames(data)

# I need a long format
data_long <- data %>%
  rownames_to_column %>%
  gather(key = 'key', value = 'value', -rowname)

# parameters
circos.clear()
circos.par(start.degree = 90, gap.degree = 4, track.margin = c(-0.1, 0.1), points.overflow.warning = FALSE)
par(mar = rep(0, 4))

# color palette
mycolor <- viridis(10, alpha = 1, begin = 0, end = 1, option = "D")
mycolor <- mycolor[sample(1:10)]

# Base plot
chordDiagram(
  x = data_long, 
  grid.col = mycolor,
  transparency = 0.25,
  directional = 1,
  direction.type = c("arrows", "diffHeight"), 
  diffHeight  = -0.04,
  annotationTrack = "grid", 
  annotationTrackHeight = c(0.05, 0.1),
  link.arr.type = "big.arrow", 
  link.sort = TRUE, 
  link.largest.ontop = TRUE)

# Add text and axis
circos.trackPlotRegion(
  track.index = 1, 
  bg.border = NA, 
  panel.fun = function(x, y) {
    
    xlim = get.cell.meta.data("xlim")
    sector.index = get.cell.meta.data("sector.index")
    
    # Add names to the sector. 
    circos.text(
      x = mean(xlim), 
      y = 3.2, 
      labels = sector.index, 
      facing = "bending", 
      cex = 0.8
      )

    # Add graduation on axis
    circos.axis(
      h = "top", 
      major.at = seq(from = 0, to = xlim[2], by = ifelse(test = xlim[2]>10, yes = 2, no = 1)), 
      minor.ticks = 1, 
      major.tick.percentage = 0.5,
      labels.niceFacing = FALSE)
  }
)
```

### Multilayer
```{r}
A1 <- c(316, 556, 367, 378)

A2 <- c(343, 584, 220, 789)

A3 <- c(378, 742, 100, 900)

A4 <- c(673, 673, 540, 50)

mat1 <- rbind(A1,A2,A3,A4)

rownames(mat1) <- c("spring-C", "summer-C", "winter-C", "autumn-C")

colnames(mat1) <- c("spring-B", "summer-B", "winter-B", "autumn-B")

B1 <- c(20, 400, 370, 10)

B2 <- c(897, 56, 29, 100)

B3 <- c(562, 165, 90, 0)

B4 <- c(673, 673, 40, 50)

mat2 <- rbind(B1,B2,B3,B4)

rownames(mat2) <- c("spring-C", "summer-C", "winter-C", "autumn-C")

colnames(mat2) <- c("spring-K", "summer-K", "winter-K", "autumn-K")

C1 <- c(280, 40, 570, 190)

C2 <- c(797, 36, 29, 109)

C3 <- c(162, 565, 10, 90)

C4 <- c(273, 603, 50, 40)

mat3 <- rbind(C1,C2,C3,C4)

rownames(mat3) <- c("spring-B", "summer-B", "winter-B", "autumn-B")

colnames(mat3) <- c("spring-K", "summer-K", "winter-K", "autumn-K")

D1 <- c(18, 200, 30, 810)

D2 <- c(97, 56, 929, 111)

D3 <- c(52, 365, 90, 10)

D4 <- c(66, 173, 30, 90)

mat4 <- rbind(D1,D2,D3,D4)

rownames(mat4) <- c("spring-B", "summer-B", "winter-B", "autumn-B")

colnames(mat4) <- c("spring-S", "summer-S", "winter-S", "autumn-S")


mat = matrix(0, nrow = 8, ncol = 12)
rownames(mat) = c(rownames(mat2), rownames(mat3))
colnames(mat) = c(colnames(mat1), colnames(mat2),colnames(mat4))
mat[rownames(mat1), colnames(mat1)] = mat1
mat[rownames(mat2), colnames(mat2)] = mat2
mat[rownames(mat3), colnames(mat3)] = mat3
mat[rownames(mat4), colnames(mat4)] = mat4
mat

```

### New chord diagram
```{r}
library(circlize)
par(bg = "black") 
#set image background color is black
#plot circos and create a network:
chordDiagram(mat, annotationTrack = c("grid", "axis"), directional = 1, transparency = 0, preAllocateTracks = list( track.height = uh(4, "mm"), track.margin = c(uh(4, "mm"), 0) ))
#add a text in each sector 
circos.track(track.index = 2, panel.fun = function(x, y) {
  sector.index = get.cell.meta.data("sector.index")
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  circos.text(mean(xlim), mean(ylim), sector.index, col = "white", cex = 0.6, niceFacing = TRUE)
})


#add a distic sector in each 
highlight.sector(rownames(mat1), track.index = 1, col = "red", text = "Chitwan", cex = 0.8, text.col = "white", niceFacing = TRUE)
highlight.sector(colnames(mat1), track.index = 1, col = "green", text = "Bardia", cex = 0.8, text.col = "white", niceFacing = TRUE)
highlight.sector(colnames(mat2), track.index = 1, col = "blue", text = "Khaptad", cex = 0.8, text.col = "white", niceFacing = TRUE)
highlight.sector(colnames(mat4), track.index = 1, col = "black", text = "Suklaphata", cex = 0.8, text.col = "white", niceFacing = TRUE)
circos.clear()

circos.track(track.index = 2, panel.fun = function(x, y) {
    if(abs(CELL_META$cell.start.degree - CELL_META$cell.end.degree) > 3) {
        sn = CELL_META$sector.index
        i_state = as.numeric(gsub("(C|R)_", "", sn))
        circos.text(CELL_META$xcenter, CELL_META$ycenter, i_state, col = "white", 
            font = 2, cex = 0.7, adj = c(0.5, 0.5), niceFacing = TRUE)
        xlim = CELL_META$xlim
        breaks = seq(0, xlim[2], by = 4e5)
        circos.axis(major.at = breaks, labels = paste0(breaks/1000, "KB"), labels.cex = 0.5)
    }
}, bg.border = NA)
```


### Chord diagram

```{r}
load("data/chromatin_transition.RData")
```
### chord diagram
```{r}
mat3 = matrix(rnorm(25), 5)
colnames(mat3) = letters[1:5]
cor_mat = cor(mat3)
col_fun = colorRamp2(c(-1, 0, 1), c("green", "white", "red"))
chordDiagram(cor_mat, grid.col = 1:5, symmetric = TRUE, col = col_fun)
title("symmetric = TRUE")
chordDiagram(cor_mat, grid.col = 1:5, col = col_fun)
title("symmetric = FALSE")
```

